global:
  scrape_interval: 5s
  evaluation_interval: 15s

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
           - alertmanager:9093

# Load rules
rule_files:
  - "rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
        labels:
          app: "prometheus"

  #- job_name: "sample_server"
  #  static_configs:
  #    - targets: ["golang_server:8090"]
  #      labels:
  #        app: "sample_server"
  
  #- job_name: "node-exporter"
  #  static_configs:
  #    - targets: ["node-exporter:9100"]
  #      labels:
  #        app: "node-exporter"
  #- job_name: "service-x"
  #  static_configs:
  #    - targets: ["service-x:3010"]
  #      labels:
  #        app: "service-x"
  #- job_name: "service-y"
  #  static_configs:
  #    - targets: ["service-y:3010"]
  #      labels:
  #        app: "service-y"
  - job_name: "pong-backend"
    static_configs:
      - targets: ["backend:3000"]
        labels:
          app: "pong-backend"