networks:
  trans_network:
    name: trans_network
    driver: bridge
include:
  - monitoring/PrometheusGrafana/docker-compose.yaml
  - monitoring/ELK-Stack/docker-compose.yml
services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: ft_transcendence-backend
    # ports:
    #   - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env
    # Override command to run migrations on startup, then start dev server
    command: sh -c "npm run db:migrate && npm run dev"
    networks:
      - trans_network

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    image: ft_transcendence-frontend-dev
    # ports:
    #   - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_BACKEND_ORIGIN=/api
      - CHOKIDAR_USEPOLLING=true # Helper for file watching across some filesystems
    depends_on:
      - backend
    networks:
      - trans_network

  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: nginx:trans
    ports:
      - "80:80"
      - "443:443"
      - "3010:3010"
    depends_on:
      - frontend
      - backend
    networks:
      trans_network:
        aliases:
          - pongrush.game
