global:
  resolve_timeout: 5m

route:
  receiver: webhook_receiver

receivers:
  - name: webhook_receiver
    webhook_configs:
      - url: 'https://webhook.site/bbe4cdc0-7e9c-49e0-9206-1fb774109b72'
        send_resolved: false