networks:
  prom_net:
 
volumes:
  prometheus_data:
    driver: local

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus-container
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.size=500MB'
      - '--storage.tsdb.retention.time=7d'
    volumes:
      - ./prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/config/rules.yml:/etc/prometheus/rules.yml
      - prometheus_data:/prometheus
    networks:
      - prom_net
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana-enterprise:latest
    container_name: grafana-container
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 20s
    networks:
      - prom_net
    ports:
      - 3000:3000
  setup-dashboards:
    image: setup-dashboards
    build: grafana/setup-dashboards
    container_name: setup-dashboards-container
    networks:
      - prom_net
    depends_on:
      grafana:
        condition: service_healthy
    environment:
      - GRAFANA_HOST=grafana-container
  alertmanager:
    image: prom/alertmanager
    build: alertmanager
    container_name: alertmanager
    networks:
      - prom_net
    ports:
      - 9093:9093
  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    command:
      - '--path.rootfs=/host'
    volumes:
      - /:/host:ro,rslave
    networks:
      - prom_net
    ports:
      - 9100:9100
  golangServer:
    image: golangserver
    build: httpServer
    container_name: golang_server
    networks:
      - prom_net
    ports:
      - 8090:8090
  service-x:
    image: service-x
    build: service-x
    container_name: service-x
    networks:
      - prom_net
    ports:
      - 3010:3010
  service-y:
    image: service-x
    build: service-x
    container_name: service-y
    networks:
      - prom_net
    ports:
      - 3011:3010
  