services:
  es-01:
    build: es-01
    image: es-01
    container_name: es-01
    networks:
      - elk-net
    ports:
      - 9200:9200
    env_file:
      - es-01/.env
    ulimits:
      memlock: -1
    develop:
      watch:
        - action: rebuild
          path: .
          target: es-01


volumes:
  es-01-vol:
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/ELK/ElkApp2/Data/es-01
  es-certs-vol:
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/ELK/ElkApp2/Data/es-01/certs

networks:
  elk-net:
